version: '3'

services:

    redis:
        image: redis:alpine
        container_name: crypto_redis
        ports:
            - 6379:6379
        environment:
            REDIS_URL: redis://localhost:6379/0


    postgres:
        container_name: game_db
        image: postgres:12-alpine
        environment:
            POSTGRES_DB: game_db
            POSTGRES_USER: crypto
            POSTGRES_HOST_AUTH_METHOD: trust


        ports:
            - 5432:5432
