export enum Events {
    RESUME_GAME = 'RESUME_GAME',
    START_SEARCH_OPPONENT = 'START_SEARCH_OPPONENT',
    START_FIGHT = 'START_FIGHT',

    MAKE_MOVE = 'MAKE_MOVE',
    NEXT_ROUND = 'NEXT_ROUND',

    GAME_FINISHED = 'GAME_FINISHED',
}
