apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zombofight-ui
    project: games
    buildNumber: '$BUILD_NUMBER'
  name: zombofight-ui
  namespace: games
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: zombofight-ui
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate

  template:
    metadata:
      annotations:
        prometheus.io/port: '3333'
        prometheus.io/scrape: 'true'
      labels:
        app: zombofight-ui
        project: games

    spec:
      containers:
        - image: registry.digitalocean.com/crypto-animals/games-zombofighter-client:$BRANCH-$COMMIT_SHA
          imagePullPolicy: Always
          name: zombofight-ui
          ports:
            - containerPort: 3333
              name: zombofight-ui
              protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          resources:
            limits:
              cpu: 120m
              memory: 256Mi
            requests:
              cpu: 60m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3333
            initialDelaySeconds: 10
            periodSeconds: 1
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /readyz
              port: 3333
            initialDelaySeconds: 5
            periodSeconds: 1
            timeoutSeconds: 1
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
