name: App Deploy
on:
  workflow_dispatch:
    inputs:
      project:
        type: choice
        description: Project
        required: true
        default: games-zombofighter-api
        options:
          - games-zombofighter-api

jobs:
  ci:
    runs-on: self-hosted
    name: check and publish artefact
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Enable corepack
        run: corepack enable

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: npm run build ${{ github.event.inputs.project }} --production

      - name: Build version name
        run: echo "::set-output name=value::${{ github.ref_name }}-${{ github.sha }}"
        id: version

      - name: Docker build
        run: |
          docker build \
            -f ./docker/${{ github.event.inputs.project }}.Dockerfile \
            -t crypto-animals/${{ github.event.inputs.project }}:${{ steps.version.outputs.value }} \
            .

      - name: Docker push
        run: |
          docker push crypto-animals/${{ github.event.inputs.project }}:${{ steps.version.outputs.value }}


  deploy:
    needs: ci
    runs-on: self-hosted
    name: deploy ${{ github.event.inputs.project }}
    environment: production
    env:
      COMMIT_SHA: ${{ github.sha }}
      BRANCH: ${{ github.ref_name }}
    steps:
      - name: Deploy
        run: kubectl apply -f deploy/${{ github.event.inputs.project }}
