name: Deploy landing to CFP
on:
  workflow_dispatch:
    inputs:
      type:
        type: choice
        description: Type project
        required: true
        options:
          - landings
          - games
      project:
        type: choice
        description: NextJS Project
        required: true
        options:
          - launchpad
          - mint
          - zombofighter-client

jobs:
  publish:
    runs-on: self-hosted
    name: Publish to Cloudflare Pages
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Enable corepack
        run: corepack enable

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: npm run export ${{ github.event.inputs.type }}-${{ github.event.inputs.project }} --production

      - name: Deploy ${{ github.event.inputs.project }} to CFP
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_PAGES_TOKEN }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          directory: dist/apps/${{ github.event.inputs.type }}/${{ github.event.inputs.project }}/exported
          accountId: f6349a281eb5fedf7468dc0f8fbfce39
          branch: main
          projectName: ${{ github.event.inputs.project }}


