name: Deploy landing to CFP
on:
  workflow_dispatch:
    inputs:
      project:
        type: choice
        description: NextJS Project
        required: true
        options:
          - launchpad
          - mint

jobs:
  publish:
    runs-on: self-hosted
    name: Publish to Cloudflare Pages
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: 6.32.9

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - name: Build project by nextjs
        run: npm run export landings-${{ github.event.inputs.project }}

      - name: Deploy NextJS App ${{ github.event.inputs.project }} to CFP
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_PAGES_TOKEN }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          directory: dist/apps/landings/${{ github.event.inputs.project }}/exported
          accountId: f6349a281eb5fedf7468dc0f8fbfce39
          branch: main
          projectName: ${{ github.event.inputs.project }}

