name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who to greet
        required: false
        options:
          - monalisa
          - cschleiden
      message:
        required: true
        description: Message
        type: string
      use-emoji:
        type: boolean
        required: false
        description: Include  emojis

jobs:
  greet:
    runs-on: self-hosted

    steps:
      - name: Send greeting
        run: echo "${{ github.event.inputs.message }} ${{ fromJSON('["", ""]')[github.event.inputs.use-emoji == 'true'] }} ${{ github.event.inputs.name }}"
